blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/kthchew/ExtendFS/discussions
    about: Ask general questions that are not bug reports or feature requests.
